[features]
seeds = true
skip-lint = false
[programs.localnet]
nft = "EYTCQfggY21BHxGLtZBi6VYzEAxQyxu7qYkEVmDgALHT"

[programs.devnet]
nft = "EYTCQfggY21BHxGLtZBi6VYzEAxQyxu7qYkEVmDgALHT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/johnliu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
